In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json

from apiclient.discovery import build

API_KEY = 'AIzaSyAz-CE_-iFIExd7sDArbEnYkMpOlDf21Y4'
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'
SEARCH_TEXT = 'LEGO'

youtube = build(
    YOUTUBE_API_SERVICE_NAME,
    YOUTUBE_API_VERSION,
    developerKey=API_KEY
)

response = youtube.search().list(q=SEARCH_TEXT, part='id,snippet', maxResults=100).execute()
for item in response.get('items', []):
    if item['id']['kind'] != 'youtube#channel':
        continue
    print('*' * 10)
    print(json.dumps(item, indent=2, ensure_ascii=False))
    print('*' * 10)


**********
{
  "kind": "youtube#searchResult",
  "etag": "AQ8eA987tif_2CIE0JkDMvfU3gI",
  "id": {
    "kind": "youtube#channel",
    "channelId": "UCP-Ng5SXUEt0VE-TXqRdL6g"
  },
  "snippet": {
    "publishedAt": "2005-10-22T08:37:44Z",
    "channelId": "UCP-Ng5SXUEt0VE-TXqRdL6g",
    "title": "LEGO",
    "description": "Welcome to the place dreams are built. This is the LEGO channel, your one stop shop for inspiring builds, animated series and the ...",
    "thumbnails": {
      "default": {
        "url": "https://yt3.ggpht.com/4xbg6M7JiSE4HrLO0IpPNoHJf6fgi0WlwqKJYtF8Wnmf6qoSZoQCTMUI-WY_YX7BGMGlwLX6VA=s88-c-k-c0xffffffff-no-rj-mo"
      },
      "medium": {
        "url": "https://yt3.ggpht.com/4xbg6M7JiSE4HrLO0IpPNoHJf6fgi0WlwqKJYtF8Wnmf6qoSZoQCTMUI-WY_YX7BGMGlwLX6VA=s240-c-k-c0xffffffff-no-rj-mo"
      },
      "high": {
        "url": "https://yt3.ggpht.com/4xbg6M7JiSE4HrLO0IpPNoHJf6fgi0WlwqKJYtF8Wnmf6qoSZoQCTMUI-WY_YX7BGMGlwLX6VA=s800-c-k-c0xffffffff-no-rj-mo"
      }
    },
    "

In [53]:
import googleapiclient.discovery

def get_channel_videos(channel_id, api_key, max_results=500):
    youtube = googleapiclient.discovery.build("youtube", "v3", developerKey=api_key)
    
    # Fetch the playlist ID for the channel's uploads
    channel_request = youtube.channels().list(
        part="contentDetails",
        id=channel_id
    )
    channel_response = channel_request.execute()
    print(channel_response)
    uploads_playlist_id = channel_response['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    
    # Fetch videos from the uploads playlist
    responses = []
    nextPageToken = 'start'
    counts = 0

    for i in range(0, max_results, 50):

        if(nextPageToken == 'start'):
            search_response = youtube.playlistItems().list(
            part= 'snippet',
            playlistId=uploads_playlist_id,
            maxResults = 50,
            ).execute()
            nextPageToken = search_response['nextPageToken']
        else:
            search_response = youtube.playlistItems().list(
            part= 'snippet',
            playlistId=uploads_playlist_id,
            maxResults = 50,
            pageToken = nextPageToken
            ).execute()
            try:
                nextPageToken = search_response['nextPageToken']
            except:
                nextPageToken = None

        responses.extend(search_response['items'])
        counts += len(search_response['items'])
    print
    video_ids = [item['snippet']['resourceId']['videoId'] for item in responses['items']]
    # Fetch video details
    video_request = youtube.videos().list(
        part="snippet,statistics",
        id=",".join(video_ids)
    )
    video_response = video_request.execute()
    
    videos_data = []
    for item in video_response['items']:
        video_data = {
            "title": item['snippet']['title'],
            "view_count": item['statistics']['viewCount'],
            "thumbnail": item['snippet']['thumbnails']['high']['url'],
            "publish_time": item['snippet']['publishedAt']
        }
        videos_data.append(video_data)
    
    return videos_data

# Replace with your API key and the channel ID for Lego
api_key = "AIzaSyAz-CE_-iFIExd7sDArbEnYkMpOlDf21Y4"
lego_channel_id = "UCP-Ng5SXUEt0VE-TXqRdL6g"

videos_data = get_channel_videos(lego_channel_id, api_key)
print(videos_data)


{'kind': 'youtube#channelListResponse', 'etag': 'cL8BmvcuoKZjFOv-FT3I-wOoSlI', 'pageInfo': {'totalResults': 1, 'resultsPerPage': 5}, 'items': [{'kind': 'youtube#channel', 'etag': '-BfI0enWqDVRU4dmMevL_9kLq1Y', 'id': 'UCP-Ng5SXUEt0VE-TXqRdL6g', 'contentDetails': {'relatedPlaylists': {'likes': '', 'uploads': 'UUP-Ng5SXUEt0VE-TXqRdL6g'}}}]}
[{'kind': 'youtube#playlistItem', 'etag': 'jQmm1RmsSaa-UtvTSGrxiWIhpcQ', 'id': 'VVVQLU5nNVNYVUV0MFZFLVRYcVJkTDZnLjlCTnkybjZqUGg0', 'snippet': {'publishedAt': '2024-07-15T17:15:00Z', 'channelId': 'UCP-Ng5SXUEt0VE-TXqRdL6g', 'title': 'Carros que Voam?!🏎️🔧🎈 | LEGO® City No Limits', 'description': 'Fala aí, meus cidadãos mecânicos! Liguem seus motores e buzinem, porque a Mech-Max construiu o MELHOR veículo de todos os tempos! É uma maravilha única das pistas, com, espere... UM MODO DE PILOTO AUTOMÁTICO! Parece a aquisição perfeita para a coleção do Colecionador.', 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/9BNy2n6jPh4/default.jpg', 'width': 

HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/videos returned "The request specifies an invalid filter parameter.". Details: "[{'message': 'The request specifies an invalid filter parameter.', 'domain': 'youtube.parameter', 'reason': 'invalidFilters', 'location': 'parameters.', 'locationType': 'other'}]">

In [ ]:
def YoutubePlaylistContents(id_, API_KEY):

    responses = []
    nextPageToken = 'start'
    counts = 0

    while(nextPageToken is not None):

        API_SERVICE_NAME = "youtube"
        API_VERSION = "v3"

        youtube = build(API_SERVICE_NAME, API_VERSION, developerKey=API_KEY)

        if(nextPageToken == 'start'):
            search_response = youtube.playlistItems().list(
            part= 'snippet',
            playlistId=id_,
            maxResults = 50,
            ).execute()
            nextPageToken = search_response['nextPageToken']
        else:
            search_response = youtube.playlistItems().list(
            part= 'snippet',
            playlistId=id_,
            maxResults = 50,
            pageToken = nextPageToken
            ).execute()
            try:
                nextPageToken = search_response['nextPageToken']
            except:
                nextPageToken = None

        responses.extend(search_response['items'])
        counts += len(search_response['items'])

    print('load '+str(counts)+' videos...')

    return responses

In [41]:
import json
for video in videos_data:
    print(f"Title: {video['title']}, Views: {video['view_count']}, Thumbnail: {video['thumbnail']}, Published At: {video['publish_time']}")

f = open('output.json', 'w')

#JSONを作ります
json.dump(videos_data, f, indent=4)

Title: Carros que Voam?!🏎️🔧🎈 | LEGO® City No Limits, Views: 176, Thumbnail: https://i.ytimg.com/vi/9BNy2n6jPh4/hqdefault.jpg, Published At: 2024-07-15T17:15:00Z
Title: ¡¿AUTOS FLOTADORES?! 🏎️ 🔧 🎈 | LEGO® City: Ciudad sin Límites, Views: 236, Thumbnail: https://i.ytimg.com/vi/lkS3WbogIdE/hqdefault.jpg, Published At: 2024-07-15T17:00:35Z
Title: FUGA IMPOSSÍVEL DA PRISÃO - Apenas Manobras Radicais! 🚨👮‍♂️🦈 | LEGO® City No Limits, Views: 373, Thumbnail: https://i.ytimg.com/vi/-SIT46Yk71Q/hqdefault.jpg, Published At: 2024-07-15T15:44:46Z
Title: FUGA IMPOSIBLE DE PRISIÓN – ¡SOLO ACRÓBATAS! 🚨 👮 🦈 | LEGO® City: Ciudad sin Límites, Views: 277, Thumbnail: https://i.ytimg.com/vi/QUz9NlHUzBA/hqdefault.jpg, Published At: 2024-07-15T15:42:27Z
Title: ISÄ-TYTÄR-PÄIVÄ 👨‍👧💕 | Varastetut muistot | LEGO DREAMZzz Mestarinoidan yö, Views: 26, Thumbnail: https://i.ytimg.com/vi/m6zE2UfpLjU/hqdefault.jpg, Published At: 2024-07-15T12:00:49Z


In [20]:
import requests
from PIL import Image
import numpy as np

# ファイル出力先
OUTPUT_PATH = "D:\\img"

def main():
    url = "https://i.ytimg.com/vi/1ak1pbKb2MM/hqdefault.jpg"
    get_img(url)
    img = img_array("image.jpg")


def get_img(url):
    # URLにGET通信でアクセス
    res = requests.get(url)

   # 画像をファイルに保存
    with open('image.jpg', 'wb') as f:
        f.write(res.content)

def img_array(img):
    img = np.array(Image.open(img))
    print(img.shape)
    print(img)
    return img
    

if __name__ == "__main__":
    main()

(360, 480, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [24]:
views = []
for video in videos_data:
    # url = video['thumbnail']
    # get_img(url)
    # img = img_array("image.jpg")
    views.append(int(video['view_count']))

In [26]:
ave = sum(views) / len(views)
ave
median = np.median(views)
median

310.0

In [54]:
from matplotlib import pyplot as plt

plt.hist(views, bins=20, color='skyblue')
plt.axvline(ave, color='red', linestyle='dashed', linewidth=1)
plt.axvline(median, color='green', linestyle='dashed', linewidth=1)
plt.show()

AttributeError: module 'matplotlib' has no attribute 'get_data_path'

{'kind': 'youtube#videoListResponse',
 'etag': 'YIUPVpqNjppyCWOZfL-19bLb7uk',
 'items': [],
 'pageInfo': {'totalResults': 0, 'resultsPerPage': 0}}